mqtt:
  container_name: mqtt
  image: eclipse-mosquitto
  restart: always
  volumes:
    - ./config:/mosquitto/config
    - ./data:/mosquitto/data
    - ./log:/mosquitto/log
    # - /home/pi/mosquitto/config:/mosquitto/config
    # - /home/pi/mosquitto/data:/mosquitto/data
    # - /home/pi/mosquitto/log:/mosquitto/log
  ports:
    - 1776:1776
    - 9001:9001

